### ISSUE TITLE
Implementation plan for first story

### ISSUE THREAD

**Issue by bjchris32** [bjchris32/habicise#1]
## Story
As a user,
* I can log in as a user on the web
* I can cultivate multiple habits
* create/remove/archive
* I can check in the time with form to record what I done
* I can check in multiple times
* I can look back on the past year in the main graph
* I can look back on the previous years in the main graph

## Implementation plan

* Env setup(Devops)
  - [x] dockerize mongo
  - [x] dockerize backend
  - [x] dockerize frontend
  - [ ] install ESLint
  - [ ] CI/CD process
  - [ ] K8s integration
  - [ ] deployment on cloud services

* Backend
  - [x] habit model
  - [x] habit workflows CRUD
  - [x] checkin model
  - [x] checkin workflows MVC
  - [x] user model
  - [x] login/logout workflow MVC
 
* Frontend
  - [x] figma design
  - ...
  - [x] habit widget
  - [x] history grid widget
  - [x] daily checking widget
  - [x] display histories
  - [x] check in commitment
  - [x] user login and logout page
